### PR TITLE
Folder Structure For Website - cssref.html

### LINKED ISSUE #7: Folder Structure For Website
Hi @apoorvadwivedi670 ,

 I would like to update the folder structure of the website. As this requires basic folder for future use.

### PR DESCRIPTION
**Pull request by Ashish7129**
Hi @s-ayush2903,

I have committed and updated the code for the file cssref.html and also added some new folders. Can you please review it?

Fixes #7

### CODE REVIEW

**Comment by s-ayush2903** [comment]
Thanks for the Pull Request, LInk the issue via `Fixes #isse_number` doing this will close the Linked issue when this PR will be merged. And I'm quite engaged nowadays so no longer available to review, Hence I'll be requesting review from other maintainers

**Comment by Ashish7129** [comment]
Hey @Akshat05-tech and @apoorvadwivedi670 ,

Can you please review my PR ?

**Review by s-ayush2903 — APPROVED** [review]
LGTM

**Review by apoodwivedi — COMMENTED** [review]
Nice work

**Pull request merged**
